from enum import Enum


class WorkflowStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    DISPATCHING = "DISPATCHING"
    COLLECTING = "COLLECTING"
    INTEGRATING = "INTEGRATING"
    GENERATING_POSITIONS = "GENERATING_POSITIONS"
    EVALUATING_POSITIONS = "EVALUATING_POSITIONS"
    INTEGRATING_DECISION = "INTEGRATING_DECISION"
    WAITING_AGENT = "WAITING_AGENT"
    REVIEWING = "REVIEWING"
    REVISING = "REVISING"
    WAITING_UPSTREAM_REVISION = "WAITING_UPSTREAM_REVISION"
    WAITING_HUMAN_SELECTION = "WAITING_HUMAN_SELECTION"
    FINALIZING = "FINALIZING"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    APPROVED = "APPROVED"
    COMPLETED_REVISION = "COMPLETED_REVISION"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
