LAYER_ID = "conclusion"
MANAGER_ID = "conclusion.manager"

POSITION_GENERATOR_ID = "conclusion.position_generator"
DECISION_EVALUATOR_ID = "conclusion.decision_evaluator"
DECISION_INTEGRATOR_ID = "conclusion.decision_integrator"
QUALITY_REVIEWER_ID = "conclusion.quality_reviewer"

AGENT_IDS = [
    POSITION_GENERATOR_ID,
    DECISION_EVALUATOR_ID,
    DECISION_INTEGRATOR_ID,
    QUALITY_REVIEWER_ID,
]
AGENT_ORDER = AGENT_IDS

DISPLAY_NAMES = {
    POSITION_GENERATOR_ID: "Position Generator",
    DECISION_EVALUATOR_ID: "Decision Evaluator",
    DECISION_INTEGRATOR_ID: "Decision Integrator",
    QUALITY_REVIEWER_ID: "Conclusion Quality Reviewer",
}

REVISION_DEPENDENCIES = {
    POSITION_GENERATOR_ID: [DECISION_EVALUATOR_ID, DECISION_INTEGRATOR_ID, QUALITY_REVIEWER_ID],
    DECISION_EVALUATOR_ID: [DECISION_INTEGRATOR_ID, QUALITY_REVIEWER_ID],
    DECISION_INTEGRATOR_ID: [QUALITY_REVIEWER_ID],
}
